### ISSUE TITLE
Extension Host crashes with this extension loaded

### ISSUE THREAD

**Issue by Chovin** [swdotcom/swdc-vscode-musictime#29] opened 2020-10-27 18:08 UTC
**Describe the bug**
```paste below
extension host crashes when starting VSC with this extension enabled
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**
1. Install this extension (or enabled if the extension is installed but disabled)
2. Restart VSC
3. Notice that Extension Host has crashed and no extensions work
4. Disable the extension
5. Restart VSC (or click `Restart Extension Host`)
6. Notice that Extension Host doesn't crash and all other extensions work again

**Expected behavior**
```paste below
extension works and extension host doesn't crash
```

**ACTUAL RESULTS**

```paste below
extension host crashes
```

**Screenshots**

![image](https://user-images.githubusercontent.com/17536161/97343015-3a4e8800-1844-11eb-9314-cfa93a69e3bd.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Plugin version: Music Time for Spotify v2.0.21

**Additional context**
```paste below
I have lots of VSC windows open, not sure if that might provide some insight.

Here's also a list of the extensions I have installed:

aaron-bond.better-comments
alefragnani.project-manager
auchenberg.vscode-browser-preview
christian-kohler.path-intellisense
CoenraadS.bracket-pair-colorizer
dbaeumer.vscode-eslint
eamodio.gitlens
EditorConfig.EditorConfig
eg2.vscode-npm-script
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
formulahendry.auto-rename-tag
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
HookyQR.beautify
HookyQR.minify
hoovercj.vscode-power-mode
johnpapa.vscode-peacock
jsaulou.theme-by-language
karigari.chat
KnisterPeter.vscode-github
kruemelkatze.vscode-dashboard
lindraupe.aw-watcher-vscode
mechatroner.rainbow-csv
mhutchie.git-graph
ms-python.python
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-wsl
ms-vscode.js-debug
ms-vscode.sublime-keybindings
ms-vsliveshare.vsliveshare
mtxr.sqltools
oderwat.indent-rainbow
p1c2u.docker-compose
PKief.material-icon-theme
pranaygp.vscode-css-peek
RandomFractalsInc.vscode-data-preview
ritwickdey.LiveServer
Shan.code-settings-sync
softwaredotcom.music-time
tomsaunders.vscode-workspace-explorer
unremarkable.pico8-simple-outline
vscode-icons-team.vscode-icons
vscode.configuration-editing
vscode.debug-auto-launch
vscode.emmet
vscode.extension-editing
vscode.git
vscode.json-language-features
vscode.merge-conflict
vscode.microsoft-authentication
vscode.npm
vscode.python
vscode.search-result
vscode.typescript-language-features
WallabyJs.quokka-vscode
yzhang.markdown-all-in-one
```

**Comment by brettmstevens7** [comment] 2020-10-28 01:11
Were you by chance able to capture an error log in your console?

**Comment by Chovin** [comment] 2020-10-28 04:28
I didn’t see any error other than extension host crashing and it giving me a list if extensions that were installed. Would you happen to know how to get a more detailed error?

**Comment by FlavioAmurrioCS** [comment] 2021-01-24 07:29
I have encounter the same error. I used VS Code [Extension Bisect](https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect) to determine this extension was the cause. I thought it could have been because I am using vscode sync onto a this rebuilt machine and it logged me out, but even after logging in I get the error. I am using a 
Mac Air 2015 with Big Sur 11.1

VSCode
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
![image](https://user-images.githubusercontent.com/25621374/105623888-4f0ecd80-5deb-11eb-9fb2-83a84d487c66.png)

**Comment by otaconjh** [comment] 2021-02-25 11:24
I also have an issue with this extension. Works fine most of the time, but when I install Ionide-fsharp for F# language support, this extension causes the extension host to crash.
```
[LineLens] Config Changed event
[LineLens] Installing
[LineLens] Installed
[PipelineHints] Config Changed event
[PipelineHints] Installing
[PipelineHints] Installed
[GitIgnore] gitignore path: c:\Users\jh\code\F#\test\.gitignore
[GitIgnore] Error accessing gitignore file [Error: ENOENT: no such file or directory, open
 'c:\Users\jh\code\F#\test\.gitignore'
	at Object.openSync (fs.js:466:3)
	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
	at Object.readFileSync (fs.js:368:35)
	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
	at Ru (c:\Users\jh\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:2:490245)
        at c:\Users\jh\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:2:490460
	at Object.then (c:\Users\jh\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:1:54273)] {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'c:\\Users\\jh\\code\\F#\\test\\.gitignore'
}
```

**Comment by naquiroz** [comment] 2021-03-08 12:23
Can confirm this issue also occurs in vscode 1.54.1

**Comment by mmclead** [comment] 2021-03-09 07:07
Thanks for the update and the error report.  That's helpful

**Comment by xavluiz** [comment] 2021-03-16 15:17
We have confirmed that the latest versions 2.1.14 and 2.1.16 have the fix for this issue, thank you.

**Closed by xavluiz** 2021-03-16 15:17 UTC
Labels: bug
